<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="RepackSOTMUtilities" AfterTargets="Build">
    <Message Text="Calling ILRepack" Importance="high" />

    <ItemGroup>
      <InputAssemblies Include="$(TargetDir)JpSOTMUtilitiesTests.dll" />
      <InputAssemblies Include="$(TargetDir)JpSOTMUtilities.dll" />
    </ItemGroup>

    <ILRepack
      Parallel="true"
      InputAssemblies="@(InputAssemblies)"
      TargetKind="SameAsPrimaryAssembly"
      OutputFile="$(TargetDir)$(TargetFileName)"
      LibraryPath="$(TargetDir)"
      Union="true"
      />

    <Message Text="ILRepack completed" Importance="high" />
  </Target>
</Project>
